# Google Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: intelligent-driver-forwarder
  annotations:
    # Allow unauthenticated invocations
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Set memory and CPU limits
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        # Scale settings
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/intelligent-driver-forwarder:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "100m"
  traffic:
  - percent: 100
    latestRevision: true